[paths]
sources_dir = "./../sources"
artifacts_dir = "./../artifacts"

[tools]
refinedc = "~/.opam/refinedc-projects/bin/refinedc"
coqc = "~/.opam/refinedc-projects/bin/coqc"

[agents.spec_assist]
model = "claude-3-7-sonnet-20250219" # "openai:gpt-4o"
max_iterations = 10
enabled = true

[agents.lemma_assist]
model = "openai:gpt-4o"  # "claude-3.5-sonnet-20241022"
max_iterations = 10
enabled = false

[meta]
logging = true
