[paths]
sources_dir = "sources"  # Will be created in scaffold directory
artifacts_dir = "artifacts"  # Will be created in scaffold directory

[tools]
refinedc = "~/.opam/refinedc-projects/bin/refinedc"  # Or full path if not in PATH
coqc = "~/.opam/refinedc-projects/bin/coqc"  # Or full path if not in PATH

[agents.spec_assist]
model = "openai:gpt-4o-mini"
max_iterations = 5
[agents.lemma_assist]
model = "openai:gpt-4o-mini"  # "claude-3.5-sonnet-20241022"
max_iterations = 5

[meta]
logging = true
